
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package lexicoOCL;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NUMERO = 47;
  public static final int DOSPUNTOS = 37;
  public static final int SUBSTRING = 26;
  public static final int MINUSCULA = 24;
  public static final int DISTINTO = 3;
  public static final int VALORINICIAL = 43;
  public static final int PARENTESIS_IZQ = 39;
  public static final int INVARIANTE = 31;
  public static final int O = 41;
  public static final int XOR = 10;
  public static final int INTEGER = 32;
  public static final int METODO = 34;
  public static final int TRUNCADO = 21;
  public static final int VALORPROPIEDAD = 42;
  public static final int IDENTIFICADOR = 46;
  public static final int NOT = 11;
  public static final int AND = 9;
  public static final int IGUAL = 2;
  public static final int OR = 8;
  public static final int MINIMO = 19;
  public static final int MAYUSCULA = 25;
  public static final int CONTEXT = 27;
  public static final int EOF = 0;
  public static final int BOOLEAN = 33;
  public static final int PARENTESIS_DER = 40;
  public static final int SIZE = 23;
  public static final int error = 1;
  public static final int SELF = 30;
  public static final int MODULO = 15;
  public static final int MENOS = 13;
  public static final int MENOR = 6;
  public static final int ERROR = 48;
  public static final int ATRIBUTO = 35;
  public static final int MAYOR = 7;
  public static final int MAXIMO = 18;
  public static final int FLECHA = 38;
  public static final int PRECONDICION = 28;
  public static final int MAYOR_IGUAL = 5;
  public static final int LET = 45;
  public static final int POSTCONDICION = 29;
  public static final int VALOR_ABSOLUTO = 17;
  public static final int CONCATENACION = 22;
  public static final int REDONDEO = 20;
  public static final int DEFINICION = 44;
  public static final int MENOR_IGUAL = 4;
  public static final int DIVISION = 16;
  public static final int MULTIPLICACION = 14;
  public static final int DOBLEPUNTOS = 36;
  public static final int MAS = 12;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IGUAL",
  "DISTINTO",
  "MENOR_IGUAL",
  "MAYOR_IGUAL",
  "MENOR",
  "MAYOR",
  "OR",
  "AND",
  "XOR",
  "NOT",
  "MAS",
  "MENOS",
  "MULTIPLICACION",
  "MODULO",
  "DIVISION",
  "VALOR_ABSOLUTO",
  "MAXIMO",
  "MINIMO",
  "REDONDEO",
  "TRUNCADO",
  "CONCATENACION",
  "SIZE",
  "MINUSCULA",
  "MAYUSCULA",
  "SUBSTRING",
  "CONTEXT",
  "PRECONDICION",
  "POSTCONDICION",
  "SELF",
  "INVARIANTE",
  "INTEGER",
  "BOOLEAN",
  "METODO",
  "ATRIBUTO",
  "DOBLEPUNTOS",
  "DOSPUNTOS",
  "FLECHA",
  "PARENTESIS_IZQ",
  "PARENTESIS_DER",
  "O",
  "VALORPROPIEDAD",
  "VALORINICIAL",
  "DEFINICION",
  "LET",
  "IDENTIFICADOR",
  "NUMERO",
  "ERROR"
  };
}

